Repository code-4-u/shallwecode, pull requests merged in 2024-11, with the labels that each got.

#8 fix: security 버그 주석 처리
  backend/src/main/java/com/shallwecode/backend/config/AppConfig.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
Labels: fix

#11 chore: 샘플 백엔드 디렉토리 구조
  backend/src/main/java/com/shallwecode/backend/test/application/controller/TestController.java
  backend/src/main/java/com/shallwecode/backend/test/application/dto/TestDTO.java
  backend/src/main/java/com/shallwecode/backend/test/application/service/TestService.java
  backend/src/main/java/com/shallwecode/backend/test/domain/aggregate/Test.java
  backend/src/main/java/com/shallwecode/backend/test/domain/repository/TestRepository.java
  backend/src/main/java/com/shallwecode/backend/test/domain/service/TestDomainService.java
Labels: chore

#12 chore: 프론트 프로젝트 초기 세팅
  .github/pull_request_template.md
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/components/common/Footer.vue
  frontend/src/components/common/Header.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/src/router/user.js
  frontend/src/stores/auth.js
  frontend/src/views/Home.vue
  frontend/src/views/user/Login.vue
  frontend/vite.config.js
Labels: chore

#13 feat: 문제 조회 기능, 기본 파일 등록
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Problem.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Testcase.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/ProblemRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/TestcaseRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
Labels: feat

#15 feat: #5 회원 기능 위한 기본구조 생성
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/User.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
Labels: feat

#20 feat: Header.vue 구현
  frontend/src/App.vue
  frontend/src/assets/css/resetcss.css
  frontend/src/components/common/Header.vue
  frontend/src/router/user.js
  frontend/src/views/user/UserList.vue
Labels: feat

#18 feat: #5 회원 닉네임 수정 기능 구현
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UserUpdateDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
Labels: feat

#24 feat: 풀이 시도 관련 기능 구현
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/shallwecode/backend/config/QueryDslConfig.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/SaveTryReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Try.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/TryLanguage.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/TryRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java
  frontend/src/assets/css/resetcss.css
  frontend/src/components/common/Header.vue
  frontend/src/components/user/MyCodingRoomList.vue
  frontend/src/components/user/MyFriendManagement.vue
  frontend/src/components/user/MyInfo.vue
  frontend/src/components/user/MyNotiList.vue
  frontend/src/components/user/MyProblemList.vue
  frontend/src/router/user.js
  frontend/src/views/user/MyPage.vue
  frontend/src/views/user/MyPageTap.vue
Labels: feat

#26 feat: 커스텀 예외 처리 구현
  backend/src/main/java/com/shallwecode/backend/common/exception/CustomException.java
  backend/src/main/java/com/shallwecode/backend/common/exception/CustomExceptionHandler.java
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
Labels: feat

#31 fix: Problem 및 Testcase 사이의 관계를 양방향 매핑에서 단방향 매핑으로 수정
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Problem.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Testcase.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/TestcaseRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
Labels: fix

#32 feat: 친구 요청 백엔드 기능 구현
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/FindUserDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/SaveFriendDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/SaveFriendReqDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/SaveNotiDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Friend.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/FriendStatus.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Noti.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/NotiType.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/FriendRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/NotiRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
Labels: feat

#34 feat: 문제 상세 조회 백엔드 기능
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Problem.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/aggregate/Testcase.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
Labels: feat

#35 feat: #5 회원 가입 기능 구현
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
Labels: feat

#37 feat: 문제 목록 조회 기능
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemResListDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
Labels: feat

#38 feat: 풀이 시도 관련 기능
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/user/MyProblemList.vue
Labels: feat

#40 feat: 친구 요청 수락, 거절 백엔드 기능 구현
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/FindFriendDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UpdateFriendReqDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/FriendRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
Labels: feat

#42 feat: 풀이 시도 상세 조회
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java
  frontend/src/components/user/MyProblemList.vue
Labels: feat

#45 feat: 헤더, 마이페이지 알림 조회 백엔드 기능 구현
  backend/src/main/java/com/shallwecode/backend/user/application/controller/NotiController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/NotiResListDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/NotiService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Noti.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
Labels: feat

#48 feat: 친구 목록 조회 기능 백엔드 구현
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/FriendResListDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
Labels: feat

#50 fix: 친구 목록 조회 Accepted만 불러오도록 수정
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
Labels: fix

#51 feat: 친구 신청 목록 조회 백엔드 기능 구현
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
Labels: feat

#54 feat: 친구 삭제 기능 구현
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/FriendRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
Labels: feat

#56 feat: 알림 읽음 상태 변경 백엔드 기능 구현
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/NotiController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UpdateNotiReqDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/NotiService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/Noti.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
Labels: feat

#57 feat: 마이페이지 알림 및 친구 목록
  backend/src/main/java/com/shallwecode/backend/user/application/dto/NotiResListDTO.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
  frontend/src/App.vue
  frontend/src/components/common/Header.vue
  frontend/src/components/user/MyFriendManagement.vue
  frontend/src/components/user/MyNotiList.vue
  frontend/src/views/user/MyPageTap.vue
Labels: feat

#59 feat: 로그인 프론트 구현
  frontend/src/views/user/Login.vue
Labels: feat

#61 fix: 엔드포인트 수정
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
Labels: fix

#62 feat: 관리자 문제 목록 조회 프론트 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemListResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemOneResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  frontend/src/components/Problem/ProbListComponent.vue
  frontend/src/components/Problem/ProbListItemComponent.vue
  frontend/src/components/Problem/SearchBar.vue
  frontend/src/components/Problem/SideComponent.vue
  frontend/src/router/admin.js
  frontend/src/router/index.js
  frontend/src/views/Problem/AdminProbList.vue
Labels: feat

#66 feat: 문제 목록 검색 기능 구현
  frontend/src/components/Problem/ProbListComponent.vue
  frontend/src/components/Problem/SearchBar.vue
  frontend/src/views/Problem/AdminProbList.vue
Labels: feat

#68 feat: 문제 목록 조회 페이징 기능 구현
  frontend/src/components/Problem/PageBar.vue
  frontend/src/components/Problem/ProbListComponent.vue
  frontend/src/views/Problem/AdminProbList.vue
Labels: feat

#71 chore: DB 변경 사항을 엔티티에 반영
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/AuthType.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/SocialType.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
Labels: chore

#74 feat: 회원 조회 추가, swagger 설명 추가
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java
Labels: feat, chore

#76 feat: 코딩방 예외처리 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
Labels: feat

#78 feat: 미시도 문제, 도전한 문제, 해결한 문제를 반환 메소드 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
Labels: feat

#80 feat: 코딩방 및 회원 목록 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyCodingRoomResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  frontend/src/assets/icons/profile.svg
  frontend/src/components/user/MyCodingRoomList.vue
  frontend/src/components/user/MyInfo.vue
  frontend/src/components/user/MyNotiList.vue
  frontend/src/views/Home.vue
  frontend/src/views/user/UserList.vue
Labels: feat

#82 feat: 자바 컴파일 기능
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CompileController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/CompileReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/CompileResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CompileService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CustomClassLoader.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/JavaSourceFromString.java
Labels: feat

#85 feat: 코딩방 프론트
  .github/pull_request_template.md
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/css/resetcss.css
  frontend/src/main.js
  frontend/src/router/codingroom.js
  frontend/src/router/index.js
  frontend/src/views/codingroom/CodingRoom.vue
Labels: feat

#87 fix: WebSocket 오류 수정
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/config/ChatHandler.java
  backend/src/main/java/com/shallwecode/backend/config/WebSocketConfig.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/SendChatDTO.java
Labels: fix

#88 feat: 코딩방 및 협업 친구 예외처리 기능 구현
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/CoopRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
Labels: feat

#89 feat: 코딩방 컴포넌트 분리
  frontend/src/components/codingroom/Chat.vue
  frontend/src/components/codingroom/CodeEditor.vue
  frontend/src/components/codingroom/ProblemDescription.vue
  frontend/src/views/codingroom/CodingRoom.vue
Labels: feat

#90 fix: 에러코드 수정
  .github/pull_request_template.md
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
Labels: fix, chore

#92 fix: 이름 수정
  frontend/src/components/codingroom/ChatArea.vue
  frontend/src/views/codingroom/CodingRoom.vue
Labels: fix

#94 fix: 어드민 페이지 수정
  frontend/src/components/Problem/ProbListComponent.vue
  frontend/src/components/Problem/SideComponent.vue
  frontend/src/components/admin/PageBar.vue
  frontend/src/components/admin/ProbListComponent.vue
  frontend/src/components/admin/ProbListItemComponent.vue
  frontend/src/components/admin/SearchBar.vue
  frontend/src/components/admin/UserListComponent.vue
  frontend/src/router/admin.js
  frontend/src/views/Problem/AdminProbList.vue
  frontend/src/views/admin/AdminPage.vue
Labels: fix

#95 feat: 미시도, 시도, 푼 문제 API 프론트와 연동 #93
  frontend/src/components/user/MyInfo.vue
  frontend/src/views/Home.vue
  frontend/src/views/user/UserList.vue
Labels: feat

#97 feat: 동시 편집 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/codingroom/CodeEditor.vue
  frontend/src/main.js
  websocket-server/.gitignore
  websocket-server/index.js
  websocket-server/package-lock.json
  websocket-server/package.json
Labels: feat

#98 feat: 유저 엔티티 수정 및 유저 목록 조회 프론트 구현
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
  frontend/src/components/admin/UserListComponent.vue
  frontend/src/views/user/UserList.vue
Labels: feat, fix

#100 feat: 채팅 기능 구현
  backend/src/main/java/com/shallwecode/backend/config/ChatHandler.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/CoopUserResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/CoopUserResListDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CoopDomainServiceTest.java
  frontend/src/components/codingroom/ChatArea.vue
Labels: feat

#101 fix: 패키지 버전 수정
  websocket-server/package-lock.json
  websocket-server/package.json
Labels: fix

#102 fix: 패키지 수정
  websocket-server/package-lock.json
  websocket-server/package.json
Labels: fix

#103 feat: 소셜로그인 구현
  backend/build.gradle
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/common/util/CustomUserUtils.java
  backend/src/main/java/com/shallwecode/backend/config/AppConfig.java
  backend/src/main/java/com/shallwecode/backend/oauth2/CustomOAuth2User.java
  backend/src/main/java/com/shallwecode/backend/oauth2/OAuthAttributes.java
  backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java
  backend/src/main/java/com/shallwecode/backend/oauth2/handler/JwtAccessDeniedHandler.java
  backend/src/main/java/com/shallwecode/backend/oauth2/handler/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/shallwecode/backend/oauth2/handler/OAuth2LoginFailureHandler.java
  backend/src/main/java/com/shallwecode/backend/oauth2/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/service/JwtService.java
  backend/src/main/java/com/shallwecode/backend/oauth2/loginDTO/GoogleOAuth2UserInfo.java
  backend/src/main/java/com/shallwecode/backend/oauth2/loginDTO/KakaoOAuth2UserInfo.java
  backend/src/main/java/com/shallwecode/backend/oauth2/loginDTO/NaverOAuth2UserInfo.java
  backend/src/main/java/com/shallwecode/backend/oauth2/loginDTO/OAuth2UserInfo.java
  backend/src/main/java/com/shallwecode/backend/oauth2/service/CustomOAuth2UserService.java
  backend/src/main/java/com/shallwecode/backend/security/config/SecurityConfig.java
  backend/src/main/java/com/shallwecode/backend/security/dto/ExceptionResponse.java
  backend/src/main/java/com/shallwecode/backend/security/dto/LoginReqDTO.java
  backend/src/main/java/com/shallwecode/backend/security/filter/CustomAuthenticationFilter.java
  backend/src/main/java/com/shallwecode/backend/security/filter/JwtFilter.java
  backend/src/main/java/com/shallwecode/backend/security/handler/LoginSuccessHandler.java
  backend/src/main/java/com/shallwecode/backend/security/util/JwtUtil.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/AuthType.java
  backend/src/main/java/com/shallwecode/backend/user/domain/aggregate/UserInfo.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/UserRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
  backend/src/main/resources/application-jwt.yml
  backend/src/main/resources/application-oauth.yml
  backend/src/main/resources/application.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/Header.vue
  frontend/src/router/user.js
  frontend/src/stores/auth.js
  frontend/src/views/user/Login.vue
  frontend/src/views/user/SignUp.vue
Labels: feat

#105 chore: 소셜 로그인 오류 수정
  backend/src/main/java/com/shallwecode/backend/config/AppConfig.java
  backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
  backend/src/main/resources/application-jwt.yml
  frontend/src/views/user/SignUp.vue
Labels: fix, chore

#107 feat: 코딩방 자바 컴파일러 api 연결
  frontend/src/components/codingroom/CodeEditor.vue
  frontend/src/views/codingroom/CodingRoom.vue
Labels: feat

#108 fix: 헤더 수정
  frontend/src/components/common/Header.vue
Labels: fix

#113 fix: 소셜 로그인, 시큐리티 수정 및 회원가입, 회원 상세 조회, 로그아웃 구현
  backend/src/main/java/com/shallwecode/backend/oauth2/CustomOAuth2User.java
  backend/src/main/java/com/shallwecode/backend/oauth2/OAuthAttributes.java
  backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java
  backend/src/main/java/com/shallwecode/backend/oauth2/handler/OAuth2LoginSuccessHandler.java
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/service/JwtService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/FindUserDetailDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/UserSaveDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
  backend/src/main/resources/application-jwt.yml
  frontend/src/components/common/Header.vue
  frontend/src/stores/apiClient.js
  frontend/src/stores/auth.js
  frontend/src/views/Home.vue
  frontend/src/views/user/Login.vue
  frontend/src/views/user/SignUp.vue
Labels: feat, fix, refactor, chore

#115 fix: 로그인 문제 해결, 소셜 인증 엔드포인트 인증 필터 제거
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  frontend/src/stores/apiClient.js
  frontend/src/stores/auth.js
Labels: fix

#118 test: 회원 기본 crud 테스트 코드
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
  backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
Labels: test, chore

#120 refactor: 회원 관련 기능 리팩토링 및 기능 추가
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/NotiController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/friend/FindFriendDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/friend/FriendResListDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/friend/SaveFriendDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/friend/SaveFriendReqDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/friend/UpdateFriendReqDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/noti/NotiResListDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/noti/SaveNotiDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/noti/UpdateNotiReqDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/user/FindUserDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/user/FindUserDetailDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/user/UserSaveDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/user/UserUpdateDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/NotiService.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
Labels: feat, refactor, chore

#124 fix: 로그인후 세션별 채팅 기능 버그 수정
  backend/src/main/java/com/shallwecode/backend/config/ChatHandler.java
  backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
  frontend/src/components/codingroom/ChatArea.vue
Labels: fix

#125 feat: 회원 탈퇴 기능와 친구 프로필 조회 백엔드 기능 구현
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/friend/FindFriendDetailDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
Labels: feat

#127 chore: 백 프로젝트 토큰에서의 회원 정보 사용하는 코드로 변경 및 간단한 수정
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/NotiController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/user/UserUpdateDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
  backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
Labels: fix, chore

#128 refactor: 문제 목록, 회원 목록, 헤더, 마이페이지 프론트 리팩토링
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/oauth2/config/SecurityConfig.java
  backend/src/main/java/com/shallwecode/backend/oauth2/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemSearchFilter.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/user/FindUserListDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
  backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
  frontend/src/assets/icons/google.svg
  frontend/src/assets/icons/kakao.svg
  frontend/src/assets/icons/naver.svg
  frontend/src/assets/icons/profile-friend.svg
  frontend/src/components/codingroom/CodeEditor.vue
  frontend/src/components/common/Header.vue
  frontend/src/components/user/MyCodingRoomList.vue
  frontend/src/components/user/MyFriendManagement.vue
  frontend/src/components/user/MyInfo.vue
  frontend/src/components/user/MyNotiList.vue
  frontend/src/components/user/MyProblemList.vue
  frontend/src/views/Home.vue
  frontend/src/views/user/MyPageTap.vue
  frontend/src/views/user/UserList.vue
Labels: feat, fix, refactor

#132 feat: 문제 수정, 삭제 & 관리자 유저 조회, 삭제 기능 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemOneResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/ProblemReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/TestcaseDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/UserController.java
  backend/src/main/java/com/shallwecode/backend/user/application/dto/user/FindUserInfoDTO.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/UserDomainService.java
  frontend/src/components/admin/ProbListComponent.vue
  frontend/src/components/admin/ProbSaveComponent.vue
  frontend/src/components/admin/ProbUpdateComponent.vue
  frontend/src/components/admin/UserListComponent.vue
Labels: feat, refactor

#133 refactor: 메인, 회원 목록, 회원가입, 마이페이지, 관리자페이지 프론트 리팩토링
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  frontend/src/components/admin/PageBar.vue
  frontend/src/components/admin/ProbListComponent.vue
  frontend/src/components/admin/ProbListItemComponent.vue
  frontend/src/components/admin/SearchBar.vue
  frontend/src/components/admin/UserListComponent.vue
  frontend/src/components/user/MyProblemList.vue
  frontend/src/views/Home.vue
  frontend/src/views/admin/AdminPage.vue
  frontend/src/views/user/MyPageTap.vue
  frontend/src/views/user/SignUp.vue
  frontend/src/views/user/UserList.vue
Labels: feat, refactor

#135 feat: 도커파일, 도커컴포즈 세팅
  .gitignore
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
  websocket-server/Dockerfile
Labels: feat

#141 feat: 문제 목록 클릭시 해당 코딩방 생성 및 입장 기능 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/CodingRoomReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/test/java/com/shallwecode/backend/problem/application/service/CodingRoomServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/application/service/ProblemServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
  frontend/src/components/codingroom/ChatArea.vue
  frontend/src/components/codingroom/ProblemDescription.vue
  frontend/src/router/codingroom.js
  frontend/src/views/Home.vue
  frontend/src/views/codingroom/CodingRoom.vue
Labels: feat

#140 feat: 관리자 버튼 추가
  frontend/src/components/common/Header.vue
Labels: feat

#145 feat: 마이페이지 참여 중 코딩방 이동시 해당 코딩방으로 이동 기능 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/FindMyCodingRoomResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java
  frontend/src/components/user/MyCodingRoomList.vue
Labels: feat

#149 refactor: 백 프로젝트 간단한 리팩토링 및 코드 수정
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CompileController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/chat/SendChatDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/codingRoom/CodingRoomReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/codingRoom/FindMyCodingRoomResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/compile/CompileReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/compile/CompileResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/compile/SendCodeDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopUserResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopUserResListDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/FindProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemListResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemOneResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemSearchFilter.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/TestcaseDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/FindMyTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/FindTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/SaveTryReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CompileService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java
  backend/src/test/java/com/shallwecode/backend/problem/application/service/ProblemServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CoopDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
Labels: fix, refactor, chore

#151 feat: 관리자 유저 삭제 구현
  backend/src/main/java/com/shallwecode/backend/common/exception/ErrorCode.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/CoopRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/TryRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/FriendRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/repository/NotiRepository.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/NotiDomainService.java
  frontend/src/components/admin/UserListComponent.vue
Labels: feat

#147 test: 친구 관련 기능 테스트 코드
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CompileController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/chat/SendChatDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/codingRoom/CodingRoomReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/codingRoom/FindMyCodingRoomResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/compile/CompileReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/compile/CompileResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/compile/SendCodeDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopUserResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopUserResListDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/FindProblemResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemListResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemSearchFilter.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/FindMyTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/FindTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/SaveTryReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CompileService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/ProblemDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java
  backend/src/main/java/com/shallwecode/backend/user/application/controller/FriendController.java
  backend/src/main/java/com/shallwecode/backend/user/application/service/FriendService.java
  backend/src/main/java/com/shallwecode/backend/user/domain/service/FriendDomainService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/shallwecode/backend/problem/application/service/ProblemServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CoopDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/user/application/service/FriendServiceTest.java
  backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
Labels: test

#154 feat: 협업 초대, 협업 탈퇴 버튼 생성
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopDTO.java
  frontend/src/components/codingroom/ChatArea.vue
Labels: feat

#153 fix: 유저 수정 해결
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  frontend/src/components/admin/ProbUpdateComponent.vue
Labels: fix

#158 feat: 코딩방 생성시 confirm 창 설정 #157
  frontend/src/views/Home.vue
Labels: feat

#159 docs: ReadMe 생성 및 기본 틀 작성
  README.md
Labels: docs

#160 feat: 코딩방 친구초대 및 나가기 구현
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CoopController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CoopService.java
  frontend/src/components/admin/ProbSaveComponent.vue
  frontend/src/components/codingroom/ChatArea.vue
Labels: feat

#165 fix: import 오류 해결
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/CoopDomainServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/domain/service/ProblemDomainServiceTest.java
Labels: fix

#169 feat: 문제, 코딩방 테스트 코드 작성
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/ProblemController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/coop/CoopDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/problem/ProblemReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/ProblemService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/repository/TestcaseRepository.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
  backend/src/test/java/com/shallwecode/backend/problem/application/service/CodingRoomServiceTest.java
  backend/src/test/java/com/shallwecode/backend/problem/application/service/ProblemServiceTest.java
Labels: feat, chore

#171 test: 회원 테스트코드 구현
  backend/src/main/java/com/shallwecode/backend/user/application/service/UserService.java
  backend/src/test/java/com/shallwecode/backend/user/application/service/UserServiceTest.java
Labels: test

#170 chore: 잘못된 경로의 DTO import 오류 fix
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
Labels: chore

#175 docs: 필요한 이미지 업로드
  images/데이터베이스ERD.png
  images/요구사항명세서.png
  images/화면설계서.png
Labels: docs

#177 chore: 간단한 수정
  frontend/src/components/common/Header.vue
Labels: chore

#178 fix: 충돌 해결
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CodingRoomController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/CompileController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/controller/TryController.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/chat/SendChatDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/codingRoom/CodingRoomReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/codingRoom/FindMyCodingRoomResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/FindMyTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/FindTryResDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/dto/try$/SaveTryReqDTO.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/CodingRoomService.java
  backend/src/main/java/com/shallwecode/backend/problem/application/service/TryService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CodingRoomDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/CoopDomainService.java
  backend/src/main/java/com/shallwecode/backend/problem/domain/service/TryDomainService.java
  backend/src/test/java/com/shallwecode/backend/problem/application/service/CodingRoomServiceTest.java
  k8s_manifests/ingress-swc.yml
Labels: fix

#179 docs: readme
  README.md
  images/DDD.png
  images/논리ERD.png
  images/물리ERD.png
  images/시스템아키텍처.png
Labels: docs

#180 docs: readme
  README.md
  img.png
Labels: docs

#181 docs: readme수정
  README.md
  frontend/Dockerfile
  images/jenkins테스트결과.png
  websocket-server/Dockerfile
Labels: docs
